<?php
class EnumCatType {
	const GOVERNMENT_AND_LAW = 1;
	const ART_AND_LITERATURE = 2;
	const FOOD_AND_CATERING = 3;
	const WORK_AND_COMMERCE = 4;
	const LESSONS_AND_INSTRUCTION = 5;
	const BIOLOGY_AND_DRUGS = 6;
	const SCIENCE_AND_ASTRONOMY = 7;
	const HISTORY = 8;
	const GEOGRAPHY = 9;
	const TECHNOLOGY = 10;
	const MUSIC = 11;
	const TRAVEL_AND_VUELING = 12;
	const FINANCIAL_AND_BUSINESS = 13;
	const BEAUTY_AND_BODY = 14;
}