name: CI -> Deploy PROD
on:
  push:
    branches: [xx]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change mode
        run: |
          cp -R ./app/Config/json/_MODE/mode_production.json ./app/Config/json/mode.json

      - name: Upload FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.PATH_PROD }}/
          dangerous-clean-slate: false
          exclude: "
            - /.git
            - /.github
            - **/.git*
            - **/.git*/**
            - **/.github*
            - **/.github*/**
            - .gitignore
            - .git-ftp-ignore
            "
